# Generated by Django 2.1.3 on 2018-12-04 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdes', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdes', models.CharField(max_length=48)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderPick', models.DateTimeField()),
                ('orderStatus', models.CharField(choices=[('W', 'WAITING'), ('R', 'READY'), ('T', 'TAKE')], default='WAITING', max_length=1)),
                ('remarks', models.CharField(default='.', max_length=300)),
                ('ifSupplied', models.BooleanField(default=False)),
                ('component1', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='comp1', to='polls.Components')),
                ('component2', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='comp2', to='polls.Components')),
                ('component3', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='comp3', to='polls.Components')),
                ('component4', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='comp4', to='polls.Components')),
                ('component5', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='comp5', to='polls.Components')),
                ('extra1', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ex1', to='polls.Extras')),
                ('extra2', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ex2', to='polls.Extras')),
                ('extra3', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ex3', to='polls.Extras')),
                ('extra4', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ex4', to='polls.Extras')),
                ('extra5', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ex5', to='polls.Extras')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('ifReady', models.IntegerField()),
                ('extra1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex11', to='polls.Extras')),
                ('extra2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex21', to='polls.Extras')),
                ('extra3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex31', to='polls.Extras')),
                ('extra4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex41', to='polls.Extras')),
                ('extra5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex51', to='polls.Extras')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdes', models.CharField(max_length=48)),
                ('stock', models.FloatField(default=0.0)),
                ('lt', models.FloatField(default=1.0)),
                ('sshigh', models.FloatField(default=0)),
                ('sslow', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartsInProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.FloatField(default=0.0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Part')),
            ],
        ),
        migrations.CreateModel(
            name='POrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porderDate', models.DateField()),
                ('ifSupplied', models.CharField(max_length=1)),
                ('orderStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Order')),
            ],
        ),
        migrations.CreateModel(
            name='POrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.FloatField(max_length=200)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdes', models.CharField(max_length=48)),
                ('price', models.IntegerField(default=0)),
                ('prep', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SupPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=200)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Part')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_des', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='porderitem',
            name='porder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Supplier'),
        ),
        migrations.AddField(
            model_name='porder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Supplier'),
        ),
        migrations.AddField(
            model_name='partsinproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
        ),
        migrations.AddField(
            model_name='part',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Unit'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro1', to='polls.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product2',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, related_name='pro2', to='polls.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product3',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, related_name='pro3', to='polls.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extras',
            name='productExtra',
            field=models.ManyToManyField(to='polls.Product'),
        ),
        migrations.AddField(
            model_name='components',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='supprice',
            unique_together={('supplier', 'part')},
        ),
        migrations.AlterUniqueTogether(
            name='porderitem',
            unique_together={('part', 'porder')},
        ),
        migrations.AlterUniqueTogether(
            name='partsinproduct',
            unique_together={('part', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('product', 'order')},
        ),
    ]
