# Generated by Django 2.1.1 on 2018-11-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdes', models.CharField(max_length=48)),
                ('stock', models.FloatField(default=0.0)),
                ('lt', models.FloatField(default=1.0)),
                ('sshigh', models.FloatField(default=0)),
                ('sslow', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartsInProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.FloatField(default=0.0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdes', models.CharField(max_length=48)),
                ('price', models.IntegerField(default=0)),
                ('prep', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Producttemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_des', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='producttemo',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Supplier'),
        ),
        migrations.AddField(
            model_name='partsinproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
        ),
        migrations.AddField(
            model_name='part',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='partsinproduct',
            unique_together={('part', 'product')},
        ),
    ]
