# Generated by Django 2.1.2 on 2018-11-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='producttemo',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Producttemo',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
