# Generated by Django 2.1.3 on 2018-12-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181208_1855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='extra1',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='extra2',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='extra3',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='extra4',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='extra5',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='extras',
            name='productExtra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='extras',
            unique_together={('part', 'productExtra')},
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='productExtra',
        ),
    ]
