# Generated by Django 2.1.3 on 2018-12-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181208_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='productExtra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='porder',
            name='orderStatus',
            field=models.CharField(choices=[('W', 'WAITING'), ('R', 'READY'), ('T', 'TAKE')], default='WAITING', max_length=1),
        ),
    ]
