# Generated by Django 2.1.2 on 2018-11-09 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181109_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=48),
            preserve_default=False,
        ),
    ]
