# Generated by Django 2.1.3 on 2018-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181208_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='POrder',
            new_name='Pord',
        ),
        migrations.AddField(
            model_name='supprice',
            name='slug',
            field=models.SlugField(default='STRING'),
        ),
    ]
