# Generated by Django 2.1.2 on 2018-11-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_part_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
