# Generated by Django 2.1.3 on 2018-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181208_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pord',
            name='porderDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
