# Generated by Django 2.1.3 on 2018-12-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20181208_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pord',
            new_name='POrder',
        ),
        migrations.RenameField(
            model_name='extras',
            old_name='productExtra',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='extras',
            unique_together={('part', 'product')},
        ),
    ]
