# Generated by Django 2.1.1 on 2018-11-16 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_auto_20181112_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra1', models.CharField(max_length=200)),
                ('extra2', models.CharField(max_length=200)),
                ('extra3', models.CharField(max_length=200)),
                ('extra4', models.CharField(max_length=200)),
                ('extra5', models.CharField(max_length=200)),
                ('quant', models.IntegerField()),
                ('ifReady', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(verbose_name='date published')),
                ('orderStatus', models.CharField(choices=[('W', 'WAITING'), ('R', 'READY'), ('T', 'TAKE')], default='WAITING', max_length=1)),
                ('remarks', models.CharField(max_length=300)),
                ('ifSupplied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.FloatField(max_length=200)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Part')),
                ('porder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='POrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porderDate', models.DateField()),
                ('ifSupplied', models.CharField(max_length=1)),
                ('orderStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Orders')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Orders'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='porderitems',
            unique_together={('part', 'porder')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitems',
            unique_together={('product', 'order')},
        ),
    ]
