# Generated by Django 2.1.3 on 2018-12-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20181208_2139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extras',
            unique_together=set(),
        ),
    ]
