# Generated by Django 2.1.1 on 2018-11-16 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_auto_20181116_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='POrders',
            new_name='POrder',
        ),
        migrations.RenameModel(
            old_name='POrderItems',
            new_name='POrderItem',
        ),
    ]
