# Generated by Django 2.1.3 on 2018-12-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20181208_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
