# Generated by Django 2.1.3 on 2018-12-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20181208_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='product',
        ),
        migrations.AddField(
            model_name='extras',
            name='productExtra',
            field=models.ManyToManyField(to='polls.Product'),
        ),
    ]
