# Generated by Django 2.1.3 on 2018-12-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20181208_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='product',
            field=models.CharField(max_length=200),
        ),
    ]
