# Generated by Django 2.1.3 on 2018-11-18 21:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20181116_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdes', models.CharField(max_length=48)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderPick',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 21, 2, 0, 22262, tzinfo=utc)),
        ),
    ]
