# Generated by Django 2.1.3 on 2018-12-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20181208_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porder',
            name='orderStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Order'),
        ),
    ]
