# Generated by Django 2.1.3 on 2018-12-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20181208_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extras',
            old_name='part',
            new_name='pdes',
        ),
    ]
