# Generated by Django 2.1.3 on 2018-11-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20181119_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='extra1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('product', 'order')},
        ),
    ]
