# Generated by Django 2.1.3 on 2018-12-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20181208_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='product',
        ),
        migrations.AddField(
            model_name='extras',
            name='productExtra',
            field=models.ManyToManyField(to='polls.Product'),
        ),
        migrations.AlterField(
            model_name='extras',
            name='pdes',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='extras',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
