# Generated by Django 2.1.3 on 2018-11-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20181119_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='productExtra',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex1', to='polls.Extras'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex2', to='polls.Extras'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex3', to='polls.Extras'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex4', to='polls.Extras'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex5', to='polls.Extras'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
    ]
