# Generated by Django 2.1.3 on 2018-12-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20181208_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extras',
            old_name='productExtra',
            new_name='productExtra2',
        ),
    ]
