# Generated by Django 2.1.3 on 2018-11-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20181119_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='productExtra',
            field=models.ManyToManyField(to='polls.Product'),
        ),
    ]
