# Generated by Django 2.1.3 on 2018-12-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20181208_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='pdes',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='price',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='productExtra2',
        ),
        migrations.AddField(
            model_name='extras',
            name='extra_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extras',
            name='extra_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='extras',
            name='extra_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
            preserve_default=False,
        ),
    ]
