# Generated by Django 2.1.3 on 2018-11-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_extras_productextra'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('product', 'order')},
        ),
    ]
