# Generated by Django 2.1.3 on 2018-12-08 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20181208_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_price', models.FloatField(default=0.0)),
                ('extra_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Part')),
                ('extra_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Product')),
            ],
        ),
    ]
