# Generated by Django 2.1.3 on 2018-11-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20181120_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='slug',
            field=models.SlugField(default='STRING', max_length=40),
        ),
    ]
