# Generated by Django 2.1.3 on 2018-12-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_newextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra1',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ex1', to='polls.NewExtra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra2',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ex2', to='polls.NewExtra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra3',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ex3', to='polls.NewExtra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra4',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ex4', to='polls.NewExtra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra5',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ex5', to='polls.NewExtra'),
        ),
    ]
