# Generated by Django 2.1.3 on 2018-11-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_extras_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='productExtra',
        ),
    ]
