# Generated by Django 2.1.3 on 2018-11-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_remove_extras_productextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='productExtra',
            field=models.ManyToManyField(to='polls.Product'),
        ),
    ]
