# Generated by Django 2.1.3 on 2018-12-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20181208_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myextra',
            name='extra_part',
        ),
        migrations.RemoveField(
            model_name='myextra',
            name='extra_product',
        ),
        migrations.DeleteModel(
            name='MyExtra',
        ),
    ]
