# Generated by Django 2.1.3 on 2018-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_extras_productextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='STRING', max_length=40),
        ),
    ]
