# Generated by Django 2.1.3 on 2018-11-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20181120_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='product1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='222', max_length=40),
        ),
    ]
