# Generated by Django 2.1.2 on 2018-12-22 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20181217_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ifSupplied',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderPick',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 22, 12, 53, 46, 119597)),
        ),
    ]
