# Generated by Django 2.1.3 on 2018-12-23 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20181222_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderPick',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 24, 0, 58, 32, 484306)),
        ),
        migrations.AlterField(
            model_name='porder',
            name='ifSupplied',
            field=models.BooleanField(default=True),
        ),
    ]
