# Generated by Django 2.1.4 on 2019-01-04 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20181224_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='component1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp1', to='polls.Components'),
        ),
        migrations.AlterField(
            model_name='order',
            name='component2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp2', to='polls.Components'),
        ),
        migrations.AlterField(
            model_name='order',
            name='component3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp3', to='polls.Components'),
        ),
        migrations.AlterField(
            model_name='order',
            name='component4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp4', to='polls.Components'),
        ),
        migrations.AlterField(
            model_name='order',
            name='component5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp5', to='polls.Components'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex1', to='polls.NewExtra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex2', to='polls.NewExtra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex3', to='polls.NewExtra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex4', to='polls.NewExtra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex5', to='polls.NewExtra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ifSupplied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderPick',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 4, 15, 22, 25, 428765)),
        ),
        migrations.AlterField(
            model_name='order',
            name='product2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro2', to='polls.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro3', to='polls.Product'),
        ),
    ]
