# Generated by Django 2.1.4 on 2019-01-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20190104_1522'),
        ('polls', '0030_auto_20190104_1157'),
    ]

    operations = [
    ]
