# Generated by Django 2.1.2 on 2019-01-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190104_1719'),
        ('polls', '0030_auto_20190104_1157'),
    ]

    operations = [
    ]
