# Generated by Django 2.1.4 on 2019-01-04 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_merge_20190104_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='porderitem',
            name='supprice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.SupPrice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='orderPick',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 4, 20, 24, 45, 760232)),
        ),
        migrations.AlterUniqueTogether(
            name='porderitem',
            unique_together={('supprice', 'porder')},
        ),
    ]
