# Generated by Django 2.1.4 on 2019-01-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_merge_20190104_1752'),
        ('polls', '0034_auto_20190104_2029'),
        ('polls', '0031_auto_20190104_1755'),
    ]

    operations = [
    ]
