# Generated by Django 2.1.4 on 2019-01-11 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_merge_20190111_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='components',
            options={'ordering': ('product', 'part')},
        ),
        migrations.AlterModelOptions(
            name='newextra',
            options={'ordering': ('extra_product', 'extra_part')},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('pdes',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='orderPick',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 11, 11, 11, 52, 32507)),
        ),
        migrations.AlterField(
            model_name='porderitem',
            name='part',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Part'),
        ),
    ]
